export const ROWS_ADDROWS = 'ROWS_ADDROWS';

export const COLS_ADDCOLS = 'COLS_ADDCOLS';

export const CELLS_RESTORECELL = 'CELLS_RESTORECELL';

export const SELECTS_INITSELECT = 'SELECTS_INITSELECT';
export const SELECTS_UPDATESELECT = 'SELECTS_UPDATESELECT';

export const SHEET_INSERTSHEET = 'SHEET_INSERTSHEET';

export const RESTORE = 'RESTORE';


