<<<<<<< HEAD
export const ROWS_ADDROWS = 'ROWS_ADDROWS';
export const ROWS_GENERAT = 'ROWS_GENERAT';
export const ROWS_INSERTROW = 'ROWS_INSERTROW';
export const ROWS_EXECINSERTROW = 'ROWS_EXECINSERTROW';
export const ROWS_UPDATEACTIVEROWS = 'ROWS_UPDATEACTIVEROWS';
export const ROWS_RESTOREROWS = 'ROWS_RESTOREROWS';
export const ROWS_DELETEROW = 'ROWS_DELETEROW';
export const ROWS_EXECDELETEROW = 'ROWS_EXECDELETEROW';
export const ROWS_OPERROWS = 'ROWS_OPERROWS';
export const ROWS_ADJUSTHEIGHT = 'ROWS_ADJUSTHEIGHT';
export const ROWS_HIDE = 'ROWS_HIDE';
export const ROWS_EXECHIDE = 'ROWS_EXECHIDE';
export const ROWS_EXECCANCELHIDE = 'ROWS_EXECCANCELHIDE';
export const ROWS_CANCELHIDE = 'ROWS_CANCELHIDE';
export const ROWS_EXECADJUSTHEIGHT ='ROWS_EXECADJUSTHEIGHT';

export const COLS_ADDCOLS = 'COLS_ADDCOLS';
export const COLS_GENERAT = 'COLS_GENERAT';
export const COLS_INSERTCOL = 'COLS_INSERTCOL';
export const COLS_EXECINSERTCOL = 'COLS_EXECINSERTCOL';
export const COLS_UPDATEACTIVECOLS = 'COLS_UPDATEACTIVECOLS';
export const COLS_DELETECOL = 'COLS_DELETECOL';
export const COLS_EXECDELETECOL = 'COLS_EXECDELETECOL';
export const COLS_RESTORECOLS = 'COLS_RESTORECOLS';
export const COLS_OPERCOLS = 'COLS_OPERCOLS';
export const COLS_ADJUSTWIDTH = 'COLS_ADJUSTWIDTH';
export const COLS_EXECADJUSTWIDTH = 'COLS_EXECADJUSTWIDTH';
export const COLS_HIDE = 'COLS_HIDE';
export const COLS_CANCELHIDE = 'COLS_CANCELHIDE';
export const COLS_EXECHIDE = 'COLS_EXECHIDE';
export const COLS_EXECCANCELHIDE = 'COLS_EXECCANCELHIDE';


export const CELLS_RESTORECELL = 'CELLS_RESTORECELL';
export const CELLS_UPDATE = 'CELLS_UPDATE';
export const CELLS_UPDATE_PROP = 'CELLS_UPDATE_PROP';
export const CELLS_INSERTCELL = 'CELLS_INSERTCELL';
export const CELLS_UPDATE_BORDER = 'CELLS_UPDATE_BORDER';
export const CELLS_HANDLEMERGE = 'CELLS_HANDLEMERGE';
export const CELLS_MERGE = 'CELLS_MERGE';
export const CELLS_SPLIT = 'CELLS_SPLIT';

export const SELECTS_INITSELECT = 'SELECTS_INITSELECT';
export const SELECTS_UPDATESELECT = 'SELECTS_UPDATESELECT';
export const SELECTS_SWITCHSELECT = 'SELECTS_SWITCHSELECT';

export const SHEET_INSERTSHEET = 'SHEET_INSERTSHEET';
export const SHEET_FROZEN = 'SHEET_FROZEN';
export const SHEET_FIRSTCOLFROZEN = 'SHEET_FIRSTCOLFROZEN';
export const SHEET_FIRSTROWFROZEN = 'SHEET_FIRSTROWFROZEN';
export const SHEET_UNFROZEN = 'SHEET_UNFROZEN';
export const SHEET_RESTOREFROZEN = 'SHEET_RESTOREFROZEN';
export const SHEET_EXECUNFROZEN = 'SHEET_EXECUNFROZEN';
export const SHEET_POINTFROZEN = 'SHEET_POINTFROZEN';
export const SHEET_ROWFROZEN = 'SHEET_ROWFROZEN';
export const SHEET_COLFROZEN = 'SHEET_COLFROZEN';

export const EDIT_UPDATE = 'EDIT_UPDATE';
export const EDIT_SHOW = 'EDIT_SHOW';
export const EDIT_HIDE = 'EDIT_HIDE';

export const OCCUPY_UPDATE = 'OCCUPY_UPDATE';
export const OCCUPY_DELETECOL = 'OCCUPY_DELETECOL';
export const OCCUPY_DELETEROW = 'OCCUPY_DELETEROW';

export const HISTORY_REDO = 'HISTORY_REDO';
export const HISTORY_UNDO = 'HISTORY_UNDO';
export const HISTORY_ADD = 'HISTORY_ADD';


export const RESTORE = 'RESTORE';



=======
export const ROWS_ADDROWS = 'ROWS_ADDROWS'
export const ROWS_GENERAT = 'ROWS_GENERAT'
export const ROWS_INSERTROWS = 'ROWS_INSERTROWS'
export const ROWS_UPDATEACTIVEROWS = 'ROWS_UPDATEACTIVEROWS'
export const ROWS_RESTOREROWS = 'ROWS_RESTOREROWS'
export const ROWS_DELETEROWS = 'ROWS_DELETEROWS'
export const ROWS_OPERROWS = 'ROWS_OPERROWS'
export const ROWS_ADJUSTHEIGHT = 'ROWS_ADJUSTHEIGHT'
export const ROWS_HIDE = 'ROWS_HIDE'
export const ROWS_CANCELHIDE = 'ROWS_CANCELHIDE'

export const COLS_ADDCOLS = 'COLS_ADDCOLS'
export const COLS_GENERAT = 'COLS_GENERAT'
export const COLS_INSERTCOLS = 'COLS_INSERTCOLS'
export const COLS_UPDATEACTIVECOLS = 'COLS_UPDATEACTIVECOLS'
export const COLS_DELETECOLS = 'COLS_DELETECOLS'
export const COLS_RESTORECOLS = 'COLS_RESTORECOLS'
export const COLS_OPERCOLS = 'COLS_OPERCOLS'
export const COLS_ADJUSTWIDTH = 'COLS_ADJUSTWIDTH'
export const COLS_HIDE = 'COLS_HIDE'
export const COLS_CANCELHIDE = 'COLS_CANCELHIDE'

export const CELLS_RESTORECELL = 'CELLS_RESTORECELL'
export const CELLS_UPDATE = 'CELLS_UPDATE'
export const CELLS_INSERTCELL = 'CELLS_INSERTCELL'
export const CELLS_UPDATE_BORDER = 'CELLS_UPDATE_BORDER'
export const CELLS_MERGE = 'CELLS_MERGE'

export const SELECTS_INITSELECT = 'SELECTS_INITSELECT'
export const SELECTS_UPDATESELECT = 'SELECTS_UPDATESELECT'
export const SELECTS_SWITCHSELECT = 'SELECTS_SWITCHSELECT'

export const SHEET_INSERTSHEET = 'SHEET_INSERTSHEET'
export const SHEET_FROZEN = 'SHEET_FROZEN'
export const SHEET_FIRSTCOLFROZEN = 'SHEET_FIRSTCOLFROZEN'
export const SHEET_FIRSTROWFROZEN = 'SHEET_FIRSTROWFROZEN'
export const SHEET_UNFROZEN = 'SHEET_UNFROZEN'

export const EDIT_UPDATE = 'EDIT_UPDATE'
export const EDIT_SHOW = 'EDIT_SHOW'
export const EDIT_HIDE = 'EDIT_HIDE'

export const OCCUPY_UPDATE = 'OCCUPY_UPDATE'
export const OCCUPY_DELETECOL = 'OCCUPY_DELETECOL'
export const OCCUPY_DELETEROW = 'OCCUPY_DELETEROW'
export const RESTORE = 'RESTORE'
>>>>>>> master
