export const ROWS_ADDROWS = 'ROWS_ADDROWS';
export const ROWS_GENERAT = 'ROWS_GENERAT';
export const ROWS_INSERTROWS = 'ROWS_INSERTROWS';
export const ROWS_UPDATEACTIVEROWS = 'ROWS_UPDATEACTIVEROWS';
export const ROWS_RESTOREROWS = 'ROWS_RESTOREROWS';
export const ROWS_DELETEROWS = 'ROWS_DELETEROWS';
export const ROWS_OPERROWS = 'ROWS_OPERROWS';
export const ROWS_ADJUSTHEIGHT = 'ROWS_ADJUSTHEIGHT';
export const ROWS_HIDE = 'ROWS_HIDE';
export const ROWS_CANCELHIDE = 'ROWS_CANCELHIDE';

export const COLS_ADDCOLS = 'COLS_ADDCOLS';
export const COLS_GENERAT = 'COLS_GENERAT';
export const COLS_INSERTCOLS = 'COLS_INSERTCOLS';
export const COLS_UPDATEACTIVECOLS = 'COLS_UPDATEACTIVECOLS';
export const COLS_DELETECOLS = 'COLS_DELETECOLS';
export const COLS_RESTORECOLS = 'COLS_RESTORECOLS';
export const COLS_OPERCOLS = 'COLS_OPERCOLS';
export const COLS_ADJUSTWIDTH = 'COLS_ADJUSTWIDTH';
export const COLS_HIDE = 'COLS_HIDE';
export const COLS_CANCELHIDE = 'COLS_CANCELHIDE';

export const CELLS_RESTORECELL = 'CELLS_RESTORECELL';
export const CELLS_UPDATE = 'CELLS_UPDATE';
export const CELLS_INSERTCELL = 'CELLS_INSERTCELL';

export const SELECTS_INITSELECT = 'SELECTS_INITSELECT';
export const SELECTS_UPDATESELECT = 'SELECTS_UPDATESELECT';
export const SELECTS_SWITCHSELECT = 'SELECTS_SWITCHSELECT';

export const SHEET_INSERTSHEET = 'SHEET_INSERTSHEET';
export const SHEET_FROZEN = 'SHEET_FROZEN';
export const SHEET_FIRSTCOLFROZEN = 'SHEET_FIRSTCOLFROZEN';
export const SHEET_FIRSTROWFROZEN = 'SHEET_FIRSTROWFROZEN';
export const SHEET_UNFROZEN = 'SHEET_UNFROZEN';

export const EDIT_UPDATE = 'EDIT_UPDATE';
export const EDIT_SHOW = 'EDIT_SHOW';
export const EDIT_HIDE = 'EDIT_HIDE';

export const OCCUPY_UPDATE = 'OCCUPY_UPDATE';
export const OCCUPY_DELETECOL = 'OCCUPY_DELETECOL';
export const OCCUPY_DELETEROW = 'OCCUPY_DELETEROW';
export const RESTORE = 'RESTORE';



