export const ADD_ROW = 'ADD_ROW'
export const ADD_COL = 'ADD_COL'

export const M_CLEAR_SHEET = 'M_CLEAR_SHEET'
export const M_CLEAR_SELECT = 'M_CLEAR_SELECT'
export const M_CLEAR_COLS = 'M_CLEAR_COLS'
export const M_CLEAR_ROWS = 'M_CLEAR_ROWS'
export const M_CLEAR_CELLS = 'M_CLEAR_CELLS'

export const INSERT_ROW = 'INSERT_ROW'
export const INSERT_COL = 'INSERT_COL'
export const M_INSERT_CELL = 'M_INSERT_CELL'
export const INSERT_SELECT = 'INSERT_SELECT'
export const INSERT_SHEET = 'INSERT_SHEET'
export const INSERT_HISTORY = 'INSERT_HISTORY'
export const MOVE_HISTORYINDEX = 'MOVE_HISTORYINDEX'

export const M_UPDATE_POINTS = 'M_UPDATE_POINTS'
export const M_DELETE_POINTS = 'M_DELETE_POINTS'
export const UPDATE_CELL = 'UPDATE_CELL'
export const M_UPDATE_MOUSEINCELL = 'M_UPDATE_MOUSEINCELL'

export const UPDATE_ACTIVESHEET = 'UPDATE_ACTIVESHEET'
export const M_UPDATE_LOAD = 'M_UPDATE_LOAD'

export const UPDATE_SELECT = 'UPDATE_SELECT'
export const UPDATE_CELL_TEXTS = 'UPDATE_CELL_TEXTS'
export const UPDATE_EDIT = 'UPDATE_EDIT'
export const M_SELECT_UPDATE_STATE = 'M_SELECT_UPDATE_STATE'

export const CANCEL_ACTIVE_ROW = 'CANCEL_ACTIVE_ROW'
export const CANCEL_ACTIVE_COL = 'CANCEL_ACTIVE_COL'

export const ACTIVE_ROW = 'ACTIVE_ROW'
export const ACTIVE_COL = 'ACTIVE_COL'

export const UPDATE_ROW = 'UPDATE_ROW'
export const UPDATE_COL = 'UPDATE_COL'

export const UPDATE_FOCUSSTATE = 'UPDATE_FOCUSSTATE'

export const UPDATE_FROZENSTATE = 'UPDATE_FROZENSTATE'

export const UPDATE_USERVIEW = 'UPDATE_USERVIEW'

export const UPDATE_MOUSESTATE = 'UPDATE_MOUSESTATE'

export const DELETE_COL = 'DELETE_COL'
export const DELETE_ROW = 'DELETE_ROW'
export const DELETE_SELECT = 'DELETE_SELECT'
export const M_DESTORY_CELL = 'M_DESTORY_CELL'
export const UPDATE_OCCUPY = 'UPDATE_OCCUPY'

export const UPDATE_VIEW_SCROLL = 'UPDATE_VIEW_SCROLL'
export const UPDATE_VIEW_ALIAS = 'UPDATE_VIEW_ALIAS'
export const ADD_VIEW_LOADED = 'ADD_VIEW_LOADED'
export const UPDATE_VIEW_MAX = 'UPDATE_VIEW_MAX'