export const ADD_ROW = 'ADD_ROW'
export const ADD_COL = 'ADD_COL'

export const INSERT_ROW = 'INSERT_ROW'
export const INSERT_COL = 'INSERT_COL'
export const INSERT_CELL = 'INSERT_CELL'
export const INSERT_SELECT = 'INSERT_SELECT'
export const INSERT_SHEET = 'INSERT_SHEET'
export const INSERT_HISTORY = 'INSERT_HISTORY'
export const MOVE_HISTORYINDEX = 'MOVE_HISTORYINDEX'

export const UPDATE_POINTINFO = 'UPDATE_POINTINFO'
export const UPDATE_CELL = 'UPDATE_CELL'

export const UPDATE_ACTIVESHEET = 'UPDATE_ACTIVESHEET'

export const UPDATE_SELECT = 'UPDATE_SELECT'
export const UPDATE_CELL_TEXTS = 'UPDATE_CELL_TEXTS'
export const UPDATE_EDIT = 'UPDATE_EDIT'

export const CANCEL_ACTIVE_ROW = 'CANCEL_ACTIVE_ROW'
export const CANCEL_ACTIVE_COL = 'CANCEL_ACTIVE_COL'

export const ACTIVE_ROW = 'ACTIVE_ROW'
export const ACTIVE_COL = 'ACTIVE_COL'

export const UPDATE_ROW = 'UPDATE_ROW'
export const UPDATE_COL = 'UPDATE_COL'

export const UPDATE_FOCUSSTATE = 'UPDATE_FOCUSSTATE'

export const UPDATE_FROZENSTATE = 'UPDATE_FROZENSTATE'

export const UPDATE_USERVIEW = 'UPDATE_USERVIEW'

export const SWITCH_ACTIVESELECT = 'SWITCH_ACTIVESELECT'

export const UPDATE_MOUSESTATE = 'UPDATE_MOUSESTATE'

export const DELETE_COL = 'DELETE_COL'
export const DELETE_ROW = 'DELETE_ROW'

export const DELETE_CELL_POINTINFO = 'DELETE_CELL_POINTINFO'

export const UPDATE_OCCUPY = 'UPDATE_OCCUPY'